In [7]:
"""
    数组加法： 各个数组对应的元素相加
"""

import numpy as np

arr1 =  np.random.randint(5,20,size=(2,3))
arr2 =  np.random.randint(5,20,size=(2,3))
print(arr1)
print(arr2)

print(arr1 + arr2)

[[ 7 12 15]
 [12 10 10]]
[[13 12 15]
 [16 11 13]]
[[20 24 30]
 [28 21 23]]


In [8]:
"""
    numpy.add(x1, x2, /, out=None, *, where=True, casting='same_kind',
            order='K', dtype=None, subok=True)

    x1: 第一个输入数组或标量。
    x2: 第二个输入数组或标量。
    out:输出数组
    where：表示计算加法的条件
"""

arr1 =  np.random.randint(5,20,size=(2,3))
arr2 =  np.random.randint(5,20,size=(2,3))
print(arr1)
print(arr2)

print(np.add(arr1,arr2))

[[10 10 16]
 [ 8 16 18]]
[[ 9  6  7]
 [11 16 18]]
[[19 16 23]
 [19 32 36]]


In [18]:
# where: 表示计算加法的条件，如果设置为True，则在相应位置进行计算；如果 设置为False，则在相应位置不进行计算。
arr1 =  np.random.randint(5,20,size=(2,3))
arr2 =  np.random.randint(5,20,size=(2,3))
print(arr1)
print(arr2)
print(arr1>12)
# print(np.add(arr1,arr2,where=arr1>10))
print(np.add(arr1,arr2,where=np.array([[False,True,False],[True,False,True]])))

[[17  9  9]
 [ 5  7 19]]
[[14  9 17]
 [13  6 16]]
[[ True False False]
 [False False  True]]
[[17 18 11]
 [18 18 35]]


In [23]:
# out: 输出数组，数据类型必须与预期输出相符。如果提供，它必须具有与输出 相同形状的适当类型来接收结果。
arr1 =  np.random.randint(5,20,size=(2,3))
arr2 =  np.random.randint(5,20,size=(2,3))
print(arr1)
print(arr2)

# 创建一个输出数组，存储结果
arr3 = np.ones_like(arr1)  # 创建一个和arr1形状相同的零数组
print(arr3)
# arr3 = np.add(arr1,arr2)
np.add(arr1,arr2,out=arr3)
print(arr3)


[[19 14 10]
 [18 19 18]]
[[ 9  7  7]
 [10 10 12]]
[[1 1 1]
 [1 1 1]]
[[28 21 17]
 [28 29 30]]
