In [1]:
"""
    数组减法： 各个数组对应的元素相减
"""
import numpy as np
arr1 =  np.random.randint(5,20,size=(2,3))
arr2 =  np.random.randint(5,20,size=(2,3))
print(arr1)
print(arr2)
print(arr1 - arr2)

[[14 12 12]
 [ 9 11 18]]
[[ 9 18  8]
 [ 5  8 11]]
[[ 5 -6  4]
 [ 4  3  7]]


In [2]:
#函数运算
"""
    numpy.subtract(x1, x2, /, out=None, *, where=True,
    casting='same_kind', order='K', dtype=None, subok=True)
"""
arr1 = np.random.randint(5,size=(2,3))
print(arr1)
arr2 = np.random.randint(5,size=(2,3))
print(arr2)

arr3 = np.subtract(arr1,arr2)
print(arr3)

[[3 3 0]
 [2 0 1]]
[[0 1 4]
 [4 2 4]]
[[ 3  2 -4]
 [-2 -2 -3]]
