In [4]:
"""
    数组乘法： 各个数组对应的元素相乘
"""

import numpy as np
arr1 =  np.random.randint(1,10,size=(2,3))
arr2 =  np.random.randint(1,10,size=(2,3))
print(arr1)
print(arr2)
print(arr1 * arr2)

print(np.multiply(arr1,arr2))

[[6 3 1]
 [5 6 7]]
[[3 7 5]
 [6 5 2]]
[[18 21  5]
 [30 30 14]]
[[18 21  5]
 [30 30 14]]


In [5]:

# 数组的点乘：矩阵的乘法   行的数目必须等于列的数目，否则无法进行数组点乘
arr1 =  np.random.randint(1,10,size=(3,3))
arr2 =  np.random.randint(1,10,size=(3,3))
print(arr1)
print(arr2)
print(np.dot(arr1, arr2))

[[4 6 6]
 [3 2 9]
 [7 1 4]]
[[3 7 6]
 [8 2 2]
 [1 2 2]]
[[66 52 48]
 [34 43 40]
 [33 59 52]]
