In [1]:
import numpy as np
"""
    数组除法： 各个数组对应的元素相除
"""
# 符号运算
arr1 = np.random.randint(10,size=(2,2))
print(arr1)
arr2 = np.random.randint(10,size=(2,2))
print(arr2)
print(arr1/arr2)

# 函数运算 numpy.divide

print(np.divide(arr1,arr2))

[[7 2]
 [8 9]]
[[6 9]
 [4 0]]
[[1.16666667 0.22222222]
 [2.                inf]]
[[1.16666667 0.22222222]
 [2.                inf]]


C:\Users\33122\AppData\Local\Temp\ipykernel_54696\2205989608.py:10: RuntimeWarning: divide by zero encountered in divide
  print(arr1/arr2)
C:\Users\33122\AppData\Local\Temp\ipykernel_54696\2205989608.py:14: RuntimeWarning: divide by zero encountered in divide
  print(np.divide(arr1,arr2))
