In [4]:
"""
    dtype :  数组元素的数据类型
    shape :  表示维度大小的元组
    size  :  表示元素的个数
    ndim  :  维度数量
"""
import numpy as np
arr1 = np.ones((3,3))
print(arr1)
print(arr1.dtype)
print(arr1.shape)
print(arr1.size)
print(arr1.ndim)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
float64
(3, 3)
9
2
