In [6]:
"""
    split:用于沿着指定的轴分割成多个数组
    numpy.split(ary, indices_or_sections, axis=0)
    ary: 要分割的数组
    indices_or_sections：
                        可以是一个整数，表示要将数组平分成多少个子数组
                        也可以是一个整数数组，表示分割的位置
    axis：沿着哪个轴进行分割
"""
import numpy as np


# 1维 等分
arr1 = np.arange(10)
print(arr1.shape)
print(arr1)

print(np.split(arr1,2))

# 1维 索引位置分割
print(np.split(arr1,[3,6]))  #arr1[0:3],arr1[3:6],arr1[6:]
print(np.split(arr1,[3,4,6])) # arr1[0:3],arr1[3:4],arr1[4:6],arr1[6:]

(10,)
[0 1 2 3 4 5 6 7 8 9]
[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]
[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8, 9])]
[array([0, 1, 2]), array([3]), array([4, 5]), array([6, 7, 8, 9])]


In [11]:
# 2维 行方向分割
# 2等分
arr = np.random.randint(10,size=(4,3))
print("原数组:\n", arr)
print("分割结果\n",np.split(arr,4,axis=0))

# 2维 索引位置分割
print("分割结果\n",np.split(arr,[1,2],axis=0)) # arr[0:1],arr[1:2],arr[2:3],arr[3:]

原数组:
 [[3 3 5]
 [1 5 8]
 [8 4 7]
 [2 8 0]]
分割结果
 [array([[3, 3, 5]], dtype=int32), array([[1, 5, 8]], dtype=int32), array([[8, 4, 7]], dtype=int32), array([[2, 8, 0]], dtype=int32)]
分割结果
 [array([[3, 3, 5]], dtype=int32), array([[1, 5, 8]], dtype=int32), array([[8, 4, 7],
       [2, 8, 0]], dtype=int32)]


In [14]:
# 2维 列方向分割
# 3等分
arr = np.random.randint(10,size=(3,6))
print("原数组:\n", arr)
print("分割结果\n",np.split(arr,2,axis=1))

# 2维 索引位置分割
print("分割结果\n",np.split(arr,[2,4],axis=1)) # arr[0:1],arr[1:2],arr[2:3],arr[3:]

原数组:
 [[1 0 1 1 9 2]
 [8 7 1 6 4 7]
 [5 9 3 7 0 2]]
分割结果
 [array([[1, 0, 1],
       [8, 7, 1],
       [5, 9, 3]], dtype=int32), array([[1, 9, 2],
       [6, 4, 7],
       [7, 0, 2]], dtype=int32)]
分割结果
 [array([[1, 0],
       [8, 7],
       [5, 9]], dtype=int32), array([[1, 1],
       [1, 6],
       [3, 7]], dtype=int32), array([[9, 2],
       [4, 7],
       [0, 2]], dtype=int32)]


In [18]:
# 3维
arr = np.random.randint(10,size=(2,3,6))
print("原数组:\n", arr)

print("分割结果\n",np.split(arr,2,axis=0))

原数组:
 [[[0 0 6 9 8 2]
  [4 3 9 2 7 7]
  [7 6 8 3 4 3]]

 [[9 8 8 8 1 4]
  [7 4 9 6 4 1]
  [7 1 7 5 8 8]]]
分割结果
 [array([[[0, 0, 6, 9, 8, 2],
        [4, 3, 9, 2, 7, 7],
        [7, 6, 8, 3, 4, 3]]], dtype=int32), array([[[9, 8, 8, 8, 1, 4],
        [7, 4, 9, 6, 4, 1],
        [7, 1, 7, 5, 8, 8]]], dtype=int32)]


In [20]:
# 4维
arr = np.random.randint(10,size=(2,2,3,6))
print("原数组:\n", arr)

print("分割结果\n",np.split(arr,2,axis=3))

原数组:
 [[[[5 0 7 5 8 9]
   [1 1 8 9 5 8]
   [0 5 4 3 0 7]]

  [[8 9 9 4 2 6]
   [0 1 8 4 2 6]
   [7 0 9 7 0 8]]]


 [[[6 5 9 6 5 3]
   [4 6 9 9 6 2]
   [5 0 8 3 0 6]]

  [[2 9 2 4 8 4]
   [6 5 8 6 2 1]
   [5 9 0 1 9 2]]]]
分割结果
 [array([[[[5, 0, 7],
         [1, 1, 8],
         [0, 5, 4]],

        [[8, 9, 9],
         [0, 1, 8],
         [7, 0, 9]]],


       [[[6, 5, 9],
         [4, 6, 9],
         [5, 0, 8]],

        [[2, 9, 2],
         [6, 5, 8],
         [5, 9, 0]]]], dtype=int32), array([[[[5, 8, 9],
         [9, 5, 8],
         [3, 0, 7]],

        [[4, 2, 6],
         [4, 2, 6],
         [7, 0, 8]]],


       [[[6, 5, 3],
         [9, 6, 2],
         [3, 0, 6]],

        [[4, 8, 4],
         [6, 2, 1],
         [1, 9, 2]]]], dtype=int32)]
