In [1]:
"""
    hsplit: 沿着水平方向将数组分割成多个子数组
    numpy.hsplit(ary, indices_or_sections)
"""

import numpy as np

arr = np.arange(12).reshape(4,3)
print('原数组：\n',arr)

result = np.hsplit(arr,3)
print('水平方向分割成3个子数组：\n',result)



原数组：
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
水平方向分割成3个子数组：
 [array([[0],
       [3],
       [6],
       [9]]), array([[ 1],
       [ 4],
       [ 7],
       [10]]), array([[ 2],
       [ 5],
       [ 8],
       [11]])]
