In [2]:
"""
    vsplit: 沿着垂直方向将数组分割成多个子数组
    numpy.vsplit(ary, indices_or_sections)
"""

import numpy as np

arr = np.arange(12).reshape(4,3)
print('原数组：\n',arr)

result = np.vsplit(arr,2)
print('垂直方向分割成2个子数组：\n',result)



原数组：
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
垂直方向分割成2个子数组：
 [array([[0, 1, 2],
       [3, 4, 5]]), array([[ 6,  7,  8],
       [ 9, 10, 11]])]
