In [3]:
"""
    concatenate:将多个数组沿指定的轴连接起来，形成一个更大的数组
    numpy.concatenate((a1, a2, ..., arr_n), axis=0, out=None)

    NumPy 数组的轴（axis）编号从 0 开始，最外层的维度为 0 轴，向内依次递增。
    axis：整数，指定沿着哪个轴进行连接。如果不指定，默认为 0，表示第一个 轴。

    注意：(a1, a2, ..., arr_n) 这些要拼接的数组必须满足除了连接轴之外的所有维度的长度需要相同
"""
import numpy as np
# (3,2,7)   (2,4)  （2,)

arr1 = np.random.randint(10,size=(2,3))
arr2 = np.random.randint(10,size=(2,3))
print(arr1)
print(arr2)

# 垂直拼接
arr3 = np.concatenate((arr1,arr2),axis=0)
print(arr3)

[[0 7 2]
 [9 4 9]]
[[9 9 7]
 [2 0 9]]
[[0 7 2]
 [9 4 9]
 [9 9 7]
 [2 0 9]]


In [4]:
# 水平拼接
arr3 = np.concatenate((arr1,arr2),axis=1)
print(arr3)

[[0 7 2 9 9 7]
 [9 4 9 2 0 9]]
