In [3]:
"""
    stack:用于沿着新的轴连接一系列数组  （堆叠）
    numpy.concatenate基于现有的轴进行数组的拼接
    stack:总是会创建一个新的轴进行数组的拼接

    numpy.stack(arrays, axis=0, out=None)
    arrays:一系列数组，所有的数组必须具有相同的形状

    假设你有N个数组，他们的形状都相同，比如都是（m,n）
    np.stack  调用np.stack((a,b,c,...,n),axis = k)时，相当于在k的位置插入一个新的维度.
    这个新维度的大小正好等于你堆叠的数组个数。
    结果： 如果你有 N 个 (m, n) 的数组，使用 np.stack 后得到的数组形状将会是：
    当k = 0  (N,m,n)
    当k = 1  (m,N,n)
    当k = 2  (m,n,N)
"""

import numpy as np

arr1 = np.random.randint(10,size=3)
arr2 = np.random.randint(10,size=3)
print(arr1)
print(arr2)
# 垂直堆叠  （用的最多）
print(np.stack((arr1, arr2), axis=0))
# 水平堆叠
print(np.stack((arr1, arr2), axis=1))   # (0,3)  3x2


[9 3 6]
[1 7 6]
[[9 3 6]
 [1 7 6]]
[[9 1]
 [3 7]
 [6 6]]
