In [2]:
"""
    hstack : 水平堆叠  是concatenate的简化版本
    numpy.hstack(tup)
    tup：一个数组序列，它们被水平堆叠在一起。所有的数组除了1轴以外必须具有相同的形状
"""
import numpy as np

arr1 = np.random.randint(10,size=(2,3))
arr2 = np.random.randint(10,size=(2,3))
print(arr1)
print(arr2)

# 水平堆叠
print(np.hstack((arr1,arr2)))


[[0 0 4]
 [0 9 6]]
[[3 3 2]
 [4 8 8]]
[[0 0 4 3 3 2]
 [0 9 6 4 8 8]]
