In [3]:
"""
    vstack： 垂直堆叠  是 concatenate 的简化版
    numpy.vstack(tup)
    tup：一个数组序列，它们被垂直堆叠在一起。所有的数组除了0轴以外必须具有相同的形状
"""
import numpy as np
arr1 = np.random.randint(10,size=(2,3))
arr2 = np.random.randint(10,size=(2,3))
print(arr1)
print(arr2)

print(np.vstack((arr1,arr2)))

[[6 8 8]
 [0 3 6]]
[[1 1 0]
 [0 3 2]]
[[6 8 8]
 [0 3 6]
 [1 1 0]
 [0 3 2]]
