In [1]:
"""
    ndarray数组使用[]方括号进行索引
"""
import numpy as np

# 创建一维数组
arr1 =  np.array([1, 2, 3, 4, 5])
# 访问第一个元素
print(arr1[0])
# 访问最后一个元素
print(arr1[-1])

1
5


In [3]:
# 多维数组的索引
# 创建二维数组
arr1 =  np.array([[1, 2, 3], [4, 5, 6]])
print(arr1)
# 访问第1行第2列元素  2
print(arr1[0][1])
print(arr1[0,1])  # numpy独有的索引方式  表示拿第1行第2列元素

[[1 2 3]
 [4 5 6]]
2


In [4]:
arr1 =  np.array([[1, 2, 3], [4, 5, 6]])
print(arr1[0])

[1 2 3]
