In [2]:
import numpy as np
# 一维数组的切片 和 列表完全相同
arr1 = np.arange(10)
print(arr1)
# 取出 4 5 6
print(arr1[4:7])
# 取出 1 3 5
print(arr1[1:6:2])

[0 1 2 3 4 5 6 7 8 9]
[4 5 6]


In [5]:
# 多维数组的切片
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
"""
    行切片
"""
# 选择连续的多行
# 取2,3行内容
print(arr1)
print(arr1[1:])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[4 5 6]
 [7 8 9]]


In [9]:

# 选择不连续的多行
# 取1,3行内容
print(arr1[::2])

# 取3,1行内容
print(arr1[-1::-2])
print(arr1[[2,0,1]])    #numpy独有方法 可以自定义提取顺序

[[1 2 3]
 [7 8 9]]
[[7 8 9]
 [1 2 3]]
[[7 8 9]
 [1 2 3]
 [4 5 6]]


In [10]:
"""
    列切片   numpy独有方法  二维数组的切片 [行切片,列切片]
"""
# 取连续的多列
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
# 取2,3列内容3
print(arr1[:,1:])

[[2 3]
 [5 6]
 [8 9]]


In [12]:
# 取不连续的多列
# 取1,3列内容
print(arr1[:,::2])
print(arr1[:,[0,2]])

[[1 3]
 [4 6]
 [7 9]]
[[1 3]
 [4 6]
 [7 9]]


In [20]:
"""
    同时取行和列  [行切片,列切片]
"""
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr1)
# 取出第二行的第二列 第三行第三列
print(arr1[[1,2],[1,2]])    #  行和列依次组成坐标
# 取出 6 1 8
print(arr1[[1,0,2],[2,0,1]])


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[5 9]
[6 1 8]
