In [4]:
"""
    用于给数组一个新的形状而不改变其数据，它返回的是一个新的数组
    如果给定的形状与原始数据不兼容会报错
    reshape(newshape, order='C')
"""
import numpy as np

# 创建2行3列全10数组
arr1 = np.full((2,3),10)
print(arr1)
# 改变形状为3行2列
print(arr1.reshape(3, 2))

[[10 10 10]
 [10 10 10]]
[[10 10]
 [10 10]
 [10 10]]
