In [6]:
import numpy as np

"""
    resize: 用于改变数组的大小，它会直接修改调用它的原始数组，如果形状大于原始数组，则
    会在数组的末尾添加元素，这些元素尚未定义；如果新形状小于原始形状，则会截断数组

    numpy.ndarray.resize(newshape)  # newshape： 整数或元组

"""

# 创建2行3列全10数组
arr1 = np.full((2,3),10)
print(arr1)
arr1.resize(20)
print(arr1)
arr1.resize((4,3))
print(arr1)

[[10 10 10]
 [10 10 10]]
[10 10 10 10 10 10  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
[[10 10 10]
 [10 10 10]
 [ 0  0  0]
 [ 0  0  0]]
