In [5]:
import numpy as np

"""
    flatten: 返回一个一维数组，它是原始数组的拷贝，默认按
    行顺序展平数组，可以通过参数order来指定展平顺序
    numpy.ndarray.flatten(order='C')
"""

# 创建2行3列全10数组
arr1 = np.array([[5,8,2],[5,6,8]])
print(arr1)

arr2 = arr1.flatten(order='C')  # 默认按行顺序展平
print(arr2)
arr2 = arr1.flatten(order='F')  # 按列顺序展平
print(arr2)

[[5 8 2]
 [5 6 8]]
[5 8 2 5 6 8]
[5 5 8 6 2 8]
