In [1]:

"""
    ravel: 返回的是一个连续的数组，它尝试以最低的复制操作来返回展平
    后的数组
    numpy.ndarray.ravel(order='C')
"""
import numpy as np
# 创建2行3列全10数组
arr1 = np.array([[5,8,2],[5,6,8]])
print(arr1)

arr2 = arr1.ravel()  # 默认按行顺序展平
print(arr2)


[[5 8 2]
 [5 6 8]]
[5 8 2 5 6 8]


In [6]:

"""
    flatten方法 返回的是原始数组的副本，这意味着返回的新数组与原始数组是两个独立的对象，对新数组的修改不会影响原数组
    ravel 方法返回的是原数组的视图（view）或副本（copy），这取决于数组的顺序。如果数组是连续的（C-style，行优先），则 ravel 返回的是视图，这意 味着对返回数组的修改会影响到原数组。如果数组不是连续的，则 的是副本。可以通过传递 order='F' 参数来请求列优先的视图。
"""

arr1 = np.array([[5,8,2],[5,6,8]])
print(id(arr1))


arr2 = arr1.ravel(order='F')  # 默认按行顺序展平
arr2[0]=100
print(id(arr2))
print(arr1)
print(arr2)

2113103300912
2113103307920
[[5 8 2]
 [5 6 8]]
[100   5   8   6   2   8]
