In [2]:
import numpy as np
# 创建一个二维数组   # 转置 ： 行列交互
arr_2d = np.array([[1, 2], [3, 4], [5, 6]])
# 获取转置
transposed_arr = arr_2d.T
print("Original array:")
print(arr_2d)
print("Transposed array:")
print(transposed_arr)

Original array:
[[1 2]
 [3 4]
 [5 6]]
Transposed array:
[[1 3 5]
 [2 4 6]]
