In [2]:
"""
    mean: 计算数组中元素的平均值
    mean(a, axis=None, dtype=None, out=None, keepdims=false)
    a ： 原始数组
    axis：可选参数，用于指定计算平均值的轴。如果没有指定，则计算整个数组 的平均值。如果指定了轴，则计算该轴上元素的平均值。
    dtype：可选参数，用于指定返回的平均值的数据类型。如果没有指定，则通常 返回与输入数组相同的数据类型。
    keepdims：如果设置为True，计算出来的平均值保留原始数组的维度

    注意：如果数组是一个空数组，或者指定轴上的所有元素都是空值或nan则mean()会返回nan

"""
import numpy as np

#1、计算整个数据的平均值
arr1 = np.array([1,2,3,4,5])
arr_2d = np.array( [[1,2,3],
                  [4,5,6],
                  [7,8,9]])
print(np.mean(arr1))
print(np.mean(arr_2d))

3.0
5.0


In [4]:
# 2、计算指定轴上的平均值
# 按列求平均值
print(np.mean(arr_2d,axis=0))
# 按行求平均值
print(np.mean(arr_2d,axis=1))


[4. 5. 6.]
[2. 5. 8.]


In [6]:
# keepdims：如果设置为True，计算出来的平均值保留原始数组的维度
print(np.mean(arr_2d,axis=1,keepdims=True))

[[2.]
 [5.]
 [8.]]


In [11]:
#  注意：如果数组是一个空数组，或者指定轴上的所有元素都是空值或nan则mean()会返回nan

a_empty = np.array([])
print(a_empty)
print(a_empty.shape)
print(np.mean(a_empty))

[]
(0,)
nan


In [10]:
# 指定轴上有nan值
arr_2d = np.array( [[1,2,3],
                  [np.nan,5,6],
                  [np.nan,8,9]])
print(np.mean(arr_2d,axis=0))

[nan  5.  6.]
