In [2]:
"""
    sum:计算数组中所有元素的和
    sum(a, axis=None, dtype=None, out=None, keepdims=<no value>, initial=<no value>, where=<no value>)
    axis：可选参数，用于指定计算和的轴。如果没有指定，则计算整个数组的 和。如果指定了轴，则计算该轴上元素的和。可以是整数或元组，用于指定多个轴。
    dtype：可选参数，指定返回和的数据类型。如果未指定，则通常与输入数组的 类型相同，除非输入数组为布尔型，此时默认返回 int64 或 int32。
    out：可选参数，如果提供，结果会直接写入到这个数组中。这个数组必须具有 正确的形状。
    keepdims：可选参数，如果设置为 True，则计算后的和会保留原始数组的维度，其值默认为False。
    initial：可选参数，为求和提供一个初始值。这个初始值会加到求和结果中
    where：可选参数，用于指定计算和的条件。
"""

import numpy as np

arr = np.array([[1,2,3],
                [4,0,6],
                [7,8,9]])

#1、 计算整个数组中所有元素的和
print(np.sum(arr))

40


In [4]:
#2、 沿着相应方向计算总和
# 按行求和
print(np.sum(arr,axis=1))
# 按列求和
print(np.sum(arr,axis=0))

[ 6 10 24]
[12 10 18]


In [5]:
# 3、where

arr = np.array([[1,2,3],
                [4,0,6],
                [7,8,9]])

# 按列求和 并且 arr大于5
print(np.sum(arr,axis=0,where=arr>5))

[ 7  8 15]


In [6]:
# 4、initial  为求和提供一个初始值。这个初始值会加到求和结果中
arr = np.array([[1,2,3],
                [4,0,6],
                [7,8,9]])
print(np.sum(arr,axis=0,initial=100))

[112 110 118]
