In [1]:
"""
   标量与数组的运算：   2  + [1 2 3]  ->  [2 2 2] + [1 2 3] =[3,4,5]   广播机制

    广播机制 ： 当标量和数组运算时，numpy会自动扩展标量的形状，使它们能够兼容并完成逐元素的运算
"""

import numpy as np

arr1  = np.array([1,2,3])
print("arr1:\n",arr1)
print("arr1+2:\n",arr1+2)


arr1:
 [1 2 3]
arr1+2:
 [3 4 5]


In [2]:
arr1  = np.array([[1,2,3],[4,5,6]])
print("arr1:\n",arr1)
print("arr1+2:\n",arr1+2)

arr1:
 [[1 2 3]
 [4 5 6]]
arr1+2:
 [[3 4 5]
 [6 7 8]]
