In [12]:
# 导入numpy模块
import numpy as np



In [13]:
# 创建一维数组
arr1 =  np.array([1,2,3,4])
print(arr1)
print(type(arr1))

# 创建二维数组
arr2 =  np.array([[1,2,3],[4,5,6]],dtype=np.int8)  # np.int8数据范围 -128~127
print(arr2)
print(arr2.dtype)

[1 2 3 4]
<class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]]
int8


In [ ]:
"""
    order :  C(行优先)  F(列优先) K(与输入数据的存储顺序一致)  默认是K，本质上是C

    在NumPy中，“行优先”（row-major）和"列优先"（column-major）是描述多维数组（如矩阵）在内存中如何存储数据的方式。
    行优先（Row-major）：在行优先的存储顺序中，数组的行是连续存储在内存中的。这意味着，当你按顺序遍历数组时，首先遍历第一行的所有元素，然后是第二行，依此类推。在C语言中，默认的数组存储方式是行优先。
    列优先（Column-major）：在列优先的存储顺序中，数组的列是连续存储在内存中的。这意味着，当你按顺序遍历数组时，首先遍历第一列的所有元素，然后是第二列，依此类推。在Fortran语言中，默认的数组存储方式是列优先。
    NumPy默认使用行优先的存储方式，这与C语言中的数组存储方式一致。但是，NumPy也提供了方法来改变存储顺序，或者从列优先的数据源（如Fortran程序或MATLAB生成的数据）中读取数据。
    假设有一个2x3的矩阵：
    [[1, 2, 3],
     [4, 5, 6]]
    在行优先存储中，内存中的数据顺序是：1, 2, 3, 4, 5, 6
    在列优先存储中，内存中的数据顺序是：1, 4, 2, 5, 3, 6

    行优先和列优先存储顺序的不同会影响切片和索引操作的性能。
    例如，在行优先的数组中，连续地访问行元素通常会比访问列元素更快，因为在内存中它们是连续存储的。
    相反，在列优先的数组中，连续地访问列元素会更快。
"""

In [17]:
"""
copy:如果为True，则复制输入数据；
如果为False，则只有必要时才复制，
这意味着如果 object 已经是一个 NumPy 数组并且满足其他条件（如 dtype、order 相等），则不会进行复制。默认为True
"""

arr1 =  np.array([1,2,3])
arr2 = np.array(arr1,copy=True)

print("arr1:",arr1,"arr1地址：",id(arr1))
print("arr2:",arr2,"arr2地址：",id(arr2))

arr1: [1 2 3] arr1地址： 2309661037872
arr2: [1 2 3] arr2地址： 2309661038064


In [18]:
arr1 =  np.array([1,2,3])
arr2 = np.array(arr1,copy=False)  #如果参数类型都相同 不会进行复制只会对数据进行引用
print("arr1:",arr1,"arr1地址：",id(arr1))
print("arr2:",arr2,"arr2地址：",id(arr2))

arr1: [1 2 3] arr1地址： 2309661037680
arr2: [1 2 3] arr2地址： 2309661037680
