In [1]:
"""
    numpy.arange([start,] stop[, step,], dtype=None)
"""

import numpy as np

# 创建一个0-9的数组
print(np.arange(10))

[0 1 2 3 4 5 6 7 8 9]


In [2]:
# 创建一个5-14的数组,步长为2的数组
print(np.arange(5,15,2))

[ 5  7  9 11 13]


In [3]:
# 创建一个3-5的数组,步长为0.2的数组
print(np.arange(3,5,0.2))

[3.  3.2 3.4 3.6 3.8 4.  4.2 4.4 4.6 4.8]


In [4]:

print(np.arange(10,dtype=np.float16))

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
