In [5]:
"""
    zeros(shape, dtype=float, order='C', *, like=None)
    shape: 一个整数/整数元组，可以指定输出数组的形状
"""

import numpy as np
# 创建一个10个0的数组
print(np.zeros(10,dtype=np.int8))

[0 0 0 0 0 0 0 0 0 0]


In [6]:
# 创建二维全零数组
print(np.zeros((3,2)))  # 创建一个3行2列的二维数组

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [7]:
# 创建三维全零数组
print(np.zeros((3,2,4))) # 创建一个3*2*4的三维数组

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
