In [2]:
"""
    numpy.ones(shape, dtype=float, order='C')
"""

import numpy as np
# 创建一个10个1的数组
print(np.ones(10,dtype=np.float32))

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [3]:
# 创建二维全1数组
print(np.ones((3,2)))  # 创建一个3行2列的二维数组

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [4]:
# 创建三维全1数组
print(np.ones((3,2,4))) # 创建一个3*2*4的三维数组

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
